blank_issues_enabled: false
contact_links:
  - name: CurseForge Page
    url: https://www.curseforge.com/minecraft/mc-mods/cobblemon-emi-compat
    about: Download the mod or check for updates
  - name: Modrinth Page
    url: https://modrinth.com/mod/cobblemon-emi-compat
    about: Download the mod or check for updates
